version: '3.8'

services:
  health-insurance-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    volumes:
      - .:/app
    command: python app.py
