services:
  - type: web
    name: health-insurance-api
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt && python train_lightweight_model.py
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
    plan: free
